FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG MONGODB_URI
ARG AUTH_JWT_SECRET
ARG GEMINI_API_KEY

ENV MONGODB_URI=$MONGODB_URI
ENV AUTH_JWT_SECRET=$AUTH_JWT_SECRET
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000

CMD ["node", "server.js"]