apiVersion: v1
kind: Service
metadata:
  name: medilearn-service
  namespace: medilearn
spec:
  type: NodePort
  selector:
    app: medilearn
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007