apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: medilearn-monitor
  namespace: medilearn
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: medilearn
  namespaceSelector:
    matchNames:
      - medilearn
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s